name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Run Prisma Generate
        run: npx prisma generate
        env:
          DATABASE_URL: postgresql://temp:temp@localhost:5432/temp

      - name: Build Next.js App
        run: npm run build
        env:
          NEXTAUTH_SECRET: temp_secret_for_building_only
          DATABASE_URL: postgresql://temp:temp@localhost:5432/temp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_019020EE8AEA4CD394B8D00EF2733B58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EB1DECD2E83B43D38D381FDA23764FEF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74853737ACA747DF9BA9C2216809F663 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: gitgraphstudio
          package: .
